 export const Sampleproducts = [
    {
      id: 1,
      name: "Sambar Powder",
      description: "Authentic South Indian blend",
      category: "Traditional Blends",
      packaging: ["100g", "250g", "500g", "1kg", "5kg", "25kg"],
      minOrder: "25kg",
    },
    {
      id: 2,
      name: "Chicken Masala",
      description: "Rich & aromatic poultry spice",
      category: "Meat Masalas",
      packaging: ["50g", "100g", "250g", "1kg", "5kg", "25kg"],
      minOrder: "25kg",
    },
    {
      id: 3,
      name: "Mutton Masala",
      description: "Robust flavor for red meats",
      category: "Meat Masalas",
      packaging: ["50g", "100g", "250g", "1kg", "5kg", "25kg"],
      minOrder: "25kg",
    },
    {
      id: 4,
      name: "Fish Fry Masala",
      description: "Perfect coastal fish preparation",
      category: "Seafood Masalas",
      packaging: ["50g", "100g", "250g", "1kg", "5kg", "25kg"],
      minOrder: "25kg",
    },
    {
      id: 5,
      name: "Biryani Masala",
      description: "Premium aromatic rice blend",
      category: "Rice & Grain Masalas",
      packaging: ["50g", "100g", "250g", "1kg", "5kg", "25kg"],
      minOrder: "25kg",
    },
    {
      id: 6,
      name: "Garam Masala",
      description: "Classic warming spice blend",
      category: "Traditional Blends",
      packaging: ["50g", "100g", "250g", "1kg", "5kg", "25kg"],
      minOrder: "25kg",
    },
    {
      id: 7,
      name: "Turmeric Powder",
      description: "Pure & potent golden spice",
      category: "Single Spices",
      packaging: ["100g", "250g", "500g", "1kg", "5kg", "25kg"],
      minOrder: "50kg",
    },
    {
      id: 8,
      name: "Red Chili Powder",
      description: "Fiery heat with rich color",
      category: "Single Spices",
      packaging: ["100g", "250g", "500g", "1kg", "5kg", "25kg"],
      minOrder: "50kg",
    },
  ];
